// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZGEMAzlX6P5IqzcRDvVOE6NiZJu3cfLw',
    appId: '1:224287915220:web:b0f750697e6a2bba7f4f41',
    messagingSenderId: '224287915220',
    projectId: 'crud-dbms',
    authDomain: 'crud-dbms.firebaseapp.com',
    storageBucket: 'crud-dbms.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnTFoGdJ9WIN5kMP8gsZbGY2QBH2hjung',
    appId: '1:224287915220:android:d3f0b84522ddbad07f4f41',
    messagingSenderId: '224287915220',
    projectId: 'crud-dbms',
    storageBucket: 'crud-dbms.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUwvcQ_yt6mqoC3YL1uX68CLklmkMjQdw',
    appId: '1:224287915220:ios:d9f0d66681d41f537f4f41',
    messagingSenderId: '224287915220',
    projectId: 'crud-dbms',
    storageBucket: 'crud-dbms.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBUwvcQ_yt6mqoC3YL1uX68CLklmkMjQdw',
    appId: '1:224287915220:ios:d9f0d66681d41f537f4f41',
    messagingSenderId: '224287915220',
    projectId: 'crud-dbms',
    storageBucket: 'crud-dbms.appspot.com',
    iosBundleId: 'com.example.crud',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAZGEMAzlX6P5IqzcRDvVOE6NiZJu3cfLw',
    appId: '1:224287915220:web:dc0cf34bf4960f7d7f4f41',
    messagingSenderId: '224287915220',
    projectId: 'crud-dbms',
    authDomain: 'crud-dbms.firebaseapp.com',
    storageBucket: 'crud-dbms.appspot.com',
  );
}
